---
- name: Create
  hosts: localhost
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
        molecule: {}
  tasks:
    - name: Build image
      community.docker.docker_image:
        name: ubuntu:custom
        build:
          path: ../
          dockerfile: Dockerfile
        source: build
        force_source: true
        state: present

    - name: Create a container
      community.docker.docker_container:
        name: instance
        image: ubuntu:custom
        state: started
        command: ["sleep", "infinity"]
        log_driver: json-file
      register: docker

    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ docker }}"

    - name: Fail if container is not running
      when: >
        docker.container.State.ExitCode != 0 or
        not docker.container.State.Running
      ansible.builtin.include_tasks:
        file: tasks/create-fail.yml

    - name: Add container to molecule_inventory
      vars:
        inventory_partial_yaml: |
          all:
            children:
              molecule:
                hosts:
                  instance:
                    ansible_connection: community.docker.docker
      ansible.builtin.set_fact:
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}

    - name: Dump molecule_inventory
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_yaml }}
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Force inventory refresh
      ansible.builtin.meta: refresh_inventory

    - name: Fail if molecule group is missing
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}
      run_once: true # noqa: run-once[task]

# we want to avoid errors like "Failed to create temporary directory"
- name: Validate that inventory was refreshed
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Display uname info
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
